import{S as q,a as P,i as o}from"./assets/vendor-DgNwKBFL.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more"),h=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){g.insertAdjacentHTML("beforeend",s.map(e=>`
        <li class="gallery-item">
            <a class="gallery-link" href=${e.largeImageURL}>
                <img
                    class="gallery-image"
                    src="${e.webformatURL}"
                    alt="${e.tags}"
                />
                <ul class="card-info">
                    <li>likes:${e.likes}</li>
                    <li>views:${e.views}</li>
                    <li>comments:${e.comments}</li>
                    <li>downloads:${e.downloads}</li>
                </ul>
            </a>
        </li>
    `).join("")),h.refresh()}function $(){g.innerHTML="",h.refresh()}function p(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function w(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}async function b(s,e){const i=new URLSearchParams({key:"50857133-3b0b39e0288c55ff632440828",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15});try{const a=await P.get(`https://pixabay.com/api/?${i}`);if(a.data.hits.length===0)return o.error({title:"error",message:"Sorry, there are no images matching your search query. Please try again!"}),null;{const t=a.data.hits,r=a.data.totalHits;return{images:t,totalHits:r}}}catch(a){return o.error({title:"Error",message:`message: ${a.message}`}),null}}const v=document.querySelector(".form"),d=v.elements["search-text"],M=document.querySelector(".load-more");let n=1,u="";const S=15;v.addEventListener("submit",H);M.addEventListener("click",E);async function H(s){if(s.preventDefault(),n=1,d.value.trim()===""){o.warning({title:"Warning",message:"empty query"});return}u=d.value.trim(),$(),l(),p();try{const{images:e,totalHits:i}=await b(u,n),a=Math.ceil(i/S);e.length===0?o.error({title:"error",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(e),w(),n>=a&&(o.warning({title:"warning",message:"We're sorry, but you've reached the end of search results."}),l()))}catch{return o.error({title:"Error",message:"failed to fetch images"}),null}L()}async function E(s){s.preventDefault(),n+=1,l(),p();try{const{images:e,totalHits:i}=await b(u,n),a=Math.ceil(i/S);if(e.length===0)o.error({title:"error",message:"Sorry, there are no images matching your search query. Please try again!"});else{y(e),w();const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}n>=a&&(o.warning({title:"warning",message:"We're sorry, but you've reached the end of search results."}),l())}}catch{o.error({title:"Error",message:"failed to fetch images"})}L()}
//# sourceMappingURL=index.js.map
